### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by DreamPrism** [fQwQf/whup#29]
![image](https://github.com/user-attachments/assets/9ddf0ba1-4898-47db-afbd-5d0a10517c14)
Error above is shown when im trying to run the following code:
```
function foo(t : number) {
	if(t < 0) return;
	print(1+1);
	foo(t-1);
};
foo(10);
```

**Comment by fQwQf** [comment]
Hi.
The error you're encountering is related to stack frame handling, which is still in development. 
Sorry for that<(＿　＿)>

**Comment by fQwQf** [comment]
Now you can call functions recursively!🥳

Also, I notice that you are using an unsupported grammar , please change it to this:

```Typescript
function foo(t : int) {
    if(t < 0)
    {
        return;
    };
	print(1+1);
	foo(t-1);
};
foo(10);
```

![image](https://github.com/user-attachments/assets/fb9b9670-1eec-44d4-bb05-1c583e6d2b54)
Enjoy!
